- sql/001-functions.sql
- sql/001-functions_downgrade.sql
Add function to flatten jsonb functions that also return the values.
> Add flatten with values function

- ocdskingfisherviews/cli/commands/field_counts.py
- sql/002-tmp_release_and_parties.sql
Fixes to queries that returned unexpected results.
> Minor bug fixes

- sql/002-tmp_release_and_parties.sql
- sql/005-tender.sql
- sql/005-tender_downgrade.sql
- sql/007-contracts.sql
- tests/test_refresh_view.py
Reinstate including all transforms for now.
Make sure timestamps and numerics are casted properly. Fixes #16 and #7
Remove not dropped staged table.
Also adds tender_summary_with_data.  Fixes #8
> Several bugfixes.

- .travis.yml
- tests/test_refresh_view.py
This way Process doesn't need a setup.py
https://github.com/open-contracting/kingfisher-views/issues/41
> Travis - don't install Process by pip.

- docs/cli-add-view.rst
- docs/views.rst
- ocdskingfisherviews/cli/commands/add_view.py
- ocdskingfisherviews/cli/commands/base.py
- ocdskingfisherviews/cli/commands/correct_user_permissions.py
- ocdskingfisherviews/cli/commands/field_counts.py
- ocdskingfisherviews/cli/commands/refresh_views.py
- ocdskingfisherviews/correct_user_permissions.py
- ocdskingfisherviews/field_counts.py
- ocdskingfisherviews/refresh_views.py
https://github.com/open-contracting/kingfisher-views/issues/31
> 31 runnable views

- docs/cli-delete-view.rst
- docs/cli-list-views.rst
- docs/cli.rst
- ocdskingfisherviews/cli/commands/delete_view.py
- ocdskingfisherviews/cli/commands/list_views.py
https://github.com/open-contracting/kingfisher-views/issues/31
> New Delete View and list views commands

- sql/002-tmp_release_and_parties.sql
See #61 
Change the fields to bigints so they no longer overflow.
> change ids to bigints

- sql/002-tmp_release_and_parties.sql
see https://github.com/open-contracting/kingfisher-views/issues/61
> cast ids to bigints initially

- sql/002-tmp_release_and_parties.sql
https://github.com/open-contracting/kingfisher-process/issues/236
> *_with_collection should not be used any more

- ocdskingfisherviews/correct_user_permissions.py
https://github.com/open-contracting/kingfisher-views/issues/28
> Correct User Permissions - add other views

- docs/users.rst
https://github.com/open-contracting/kingfisher-views/issues/28
> Docs - Read Only Users

- docs/cli-add-view.rst
- ocdskingfisherviews/add_view.py
- ocdskingfisherviews/cli/commands/add_view.py
- tests/test_refresh_view.py
Also split out add_view into own function.
https://github.com/open-contracting/kingfisher-views/issues/65
> Add View:  Make views generate name from collection.

- ocdskingfisherviews/add_view.py
- ocdskingfisherviews/cli/commands/delete_view.py
- ocdskingfisherviews/field_counts.py
- ocdskingfisherviews/refresh_views.py
> Quote schema names

- sql/002-tmp_release_and_parties.sql
- sql/003-buyer-procuringentity-tenderer.sql
- sql/006-awards.sql
https://github.com/open-contracting/kingfisher-views/issues/45
> Use parties array instead of deprecated fields

- docs/get-started.rst
- docs/index.rst
- docs/logging.rst
- ocdskingfisherviews/add_view.py
- ocdskingfisherviews/cli/__init__.py
- ocdskingfisherviews/cli/commands/base.py
- ocdskingfisherviews/cli/commands/delete_view.py
- ocdskingfisherviews/cli/commands/field_counts.py
- ocdskingfisherviews/cli/commands/refresh_views.py
- ocdskingfisherviews/config.py
- ocdskingfisherviews/field_counts.py
- ocdskingfisherviews/refresh_views.py
- requirements.in
- requirements.txt
- requirements_dev.txt
- samples/logging-debug.json
- samples/logging.json
https://github.com/open-contracting/kingfisher-views/issues/93
https://github.com/open-contracting/kingfisher-views/issues/79
> logging: Move from logzero to logging

- sql/008-release.sql
- sql/009-drop-tmp_release_summary.sql
https://github.com/open-contracting/kingfisher-views/issues/102
> sql: Move drop table tmp_release_summary cascade to an 009 file

- .github/workflows/ci.yml
- docs/cli/setup.rst
- docs/cli/use.rst
- docs/get-started.rst
- docs/users.rst
- ocdskingfisherviews/add_view.py
- ocdskingfisherviews/cli/commands/base.py
- ocdskingfisherviews/cli/commands/delete_view.py
- ocdskingfisherviews/cli/commands/list_views.py
- ocdskingfisherviews/correct_user_permissions.py
- ocdskingfisherviews/migrations/versions/6fa01f350461_infoschema.py
- ocdskingfisherviews/migrations/versions/be8308b994ed_move_tables_to_views_schema.py
- ocdskingfisherviews/migrations/versions/cb9bf0366efa_users.py
> Move tables to views schema

- docs/adding-and-updating-views.rst
- docs/develop.rst
- docs/index.rst
Update the development docs to add information, and step by step walkthrough of making changes to the SQL files.
(From the docs sprint workshop on 10 March with @kindly, @robredpath and @pindec)
> Docs: About making changes to kfviews with SQL

- docs/definitions/awards_summary.csv
- docs/definitions/contracts_summary.csv
- docs/definitions/tender_summary.csv
- docs/definitions/tender_summary_with_data.csv
- sql/005-tender.sql
- sql/006-awards.sql
- sql/007-contracts.sql
- sql/999-docs.sql
> Add descriptions to tender, awards and contracts

- docs/definitions/release_summary.csv
- docs/definitions/release_summary_with_checks.csv
- docs/definitions/release_summary_with_data.csv
- sql/008-release.sql
- sql/999-docs.sql
> Add planning and tender document counts to release_summary

- docs/definitions/buyer_summary.csv
- sql/003-buyer-procuringentity-tenderer.sql
- sql/999-docs.sql
> Add buyer_name to buyer_summary

- sql/002-tmp_release_and_parties.sql
- sql/005-tender.sql
- sql/006-awards.sql
- sql/007-contracts.sql
https://github.com/open-contracting/kingfisher-views/issues/105
https://github.com/open-contracting/kingfisher-views/issues/106
> sql: replace || with concat_ws to reduce number of nulls 

- sql/001-functions.sql
- sql/998-foreign-key-relationships.sql
And use `IMMUTABLE STRICT`. Closes #157
> Try exception-handling instead of pattern-matching in functions

- sql/001-functions.sql
- sql/002-tmp_release_and_parties.sql
- sql/004-planning.sql
- sql/005-tender.sql
- sql/006-awards.sql
- sql/007-contracts.sql
- sql/009-drop-tmp_release_summary.sql
This doesn't change running time, but makes the SQL simpler.
> Fewer subqueries

- ocdskingfisherviews/cli.py
Fix name clash between option name and function.
> CLI:  Fix for broken fields counts in CLI.

- sql/middle/release_summary.sql
I'm reasonably sure this is the fix for #176 but I don't have an editing environment set up to test it
> Join on empty string rather than IS NULL

- docs/changelog.rst
This should be the last step in completing:
https://github.com/open-contracting/kingfisher-summarize/issues/29
> DOCS:  Add changelog entry for Field Lists changes.

- sql/middle/awards_summary.sql
- sql/middle/contracts_summary.sql
- sql/middle/parties_summary.sql
- sql/middle/planning_summary.sql
- sql/middle/release_summary.sql
- sql/middle/release_tmp.sql
- sql/middle/tender_summary.sql
> sql: Use same CASE statement in release_summary as in release_tmp

- docs/database.rst
- docs/definitions/relatedprocesses_summary.csv
- manage.py
- sql/final/docs.sql
- sql/middle/relatedprocesses_summary.sql
- tests/test_add.py
- tests/test_docs.py
https://github.com/open-contracting/kingfisher-summarize/issues/212
> sql: Add related processes table for release

- docs/querying-data.rst
I updated the name of the fields used in examples, changing the old ones by those listed in Database tables reference
> Update field names
